udpechoclient: udpechoclient.c
	gcc -Wall udpechoclient.c -o udpechoclient

udpechoserver: udpechoserver.c
	gcc -Wall udpechoserver.c -o udpechoserver

.PHONY: clean
clean:
	rm -f udpechoclient udpechoserver
